#!/bin/bash


#Initial setup of keys (make sure that none of them is pressed down)
#Add or remove keys that is needed to control the game you are trying to controll 
#name of the window that is displaying the videogame
# use cmd xwininfo for widonw information 

# USE cmd 'xev -event keyboard' to get xdotool keymap
ID="Default - Wine desktop"

#get the name of the current active window
isWindowName=$(xdotool getactivewindow getwindowname)
windowIDcmd=$(xdotool getactivewindow)

KeysUP () {

	xdotool keyup 	 --clearmodifiers --window "${ID}" "w" 
	xdotool keyup 	 --clearmodifiers --window "${ID}" "s" 
	xdotool keyup 	 --clearmodifiers --window "${ID}" "a" 
	xdotool keyup 	 --clearmodifiers --window "${ID}" "d" 
	xdotool keyup 	 --clearmodifiers --window "${ID}" "q" 
	xdotool keyup    --window "${ID}" "Shift_L" 
	xdotool keyup 	 --window "${ID}" "Control_L" 
	xdotool keyup    --window "${ID}" "space" 
	xdotool keyup    --window "${ID}" "Escape"

}



#"$<number>" indicates number passed from the python script and are a place holder for the keys being sent 

# function to interact and press buttons on keyboard and move mouse cursor to a specific location 
# you can modify this to reflect the need of your game 

#click left button on mouse only once 
ClickMouseL()
{
	xdotool click --window "${ID}" 1
}

#click right button on mouse only once 
ClickMouseR()
{
	xdotool click --window "${ID}" 3 

}

stopController()
{
	xdotool key --clearmodifiers --window "${ID}" "Escape"
}

KeysUP 

#make sure that there is a whitespace after "[" and before "]"
if [[ "${isWindowName}" == "${ID}" ]]; then

	if [[ "$1" == "start" ]]; then
		
		#send keyboard arguments
		xdotool keydown   --clearmodifiers --window "${ID}" "$2" 
		xdotool keydown   --clearmodifiers --window "${ID}" "$3" 
		xdotool keydown   --clearmodifiers --window "${ID}" "$4" 
		xdotool keydown   --clearmodifiers --window "${ID}" "$5" 
		xdotool keydown   --window "${ID}" "$6" 
		xdotool keydown   --window "${ID}" "$7" 
		xdotool keydown   --window "${ID}" "$8" 
		xdotool keydown   --clearmodifiers --window "${ID}" "$9" 
		

		#send mouse arguments
		xdotool mousemove --clearmodifiers --window "${windowIDcmd}" "${10}" "${11}" 
		${12} 
		${13}

	elif [[ "${1}" == "stop" ]]; then 
		stopController 
	fi

 	  
fi

